AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - config/compass.rb
    - public/web-assets/**/*
    - public/test-assets/**/*
  RunRailsCops: true

Lint/LiteralInInterpolation:
  Enabled: false

Lint/NumericLiterals:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    find: 'detect'

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceAfterControlKeyword:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

# Not valid for Rails 3.
Rails/ActionFilter:
  Enabled: false

# Not valid for mongoid
Rails/DefaultScope:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Exclude:
    - db/migrate/**
